### ISSUE TITLE
Older versions of the documentation should not show up by default

### ISSUE THREAD

**Issue by akosma** [vshn/embedded-search-engine#46]
This issue was brought here from https://github.com/k8up-io/k8up/issues/872

**Comment by akosma** [comment]
(Pinging @chloesoe and @davidgubler for reference to the previous version)

I'm planning to deploy a version 1.9 of this search engine with the following features:

* The search is performed _only_ on the current version currently seen by the user. That means you can switch to version 1.4 in the version picker of the Antora documentation site, and the search results will _only_ include those of version 1.4.
* If the user is in the "master" or "main" version, the search is _global_, that means that all results from all versions are returned.
* Number of results grows from 10 (current) to 50

Please confirm that this behavior is suitable, thanks!

**Comment by davidgubler** [comment]
Personally I would prefer the same behavior for master as for any version (only search the current version) but I guess it doesn't matter much.

**Comment by chloesoe** [comment]
Same thoughts as Gubi

> If the user is in the "master" or "main" version, the search is global, that means that all results from all versions are returned.

I assume that is easier technical wise? If so, then ok.
If possible I'd like if  an additional text would be added which explains that "main" will search in all versions. And we should be able to easily switch to the newest version of the documentation.

**Comment by akosma** [comment]
I'm sorry I don't understand this point. What I mean by "master" is this screenshot.

> Personally I would prefer the same behavior for master as for any version (only search the current version) but I guess it doesn't matter much.

![image](https://github.com/vshn/embedded-search-engine/assets/55348/16cd6b7c-449f-42c4-a567-43379b85bb3d)

**Comment by akosma** [comment]
The picker at the bottom of the documentation website allows you to select any version. If you select "master", then you get all results. If you're in version 2.0, you only get results from that version.

**Comment by akosma** [comment]
> Same thoughts as Gubi
> 
> > If the user is in the "master" or "main" version, the search is global, that means that all results from all versions are returned.
> 
> I assume that is easier technical wise? If so, then ok. If possible I'd like if an additional text would be added which explains that "main" will search in all versions. And we should be able to easily switch to the newest version of the documentation.

The version switching is not a responsibility of this component, but provided by Antora (see screenshot above)

The "additional text" part is not immediately obvious how to achieve.

**Comment by davidgubler** [comment]
When I select "master" I expect only search result from the "master" version of the documentation.

For me "master" is just another version of the documentation, like 2.7 or 0.1, so the search should behave the same.

**Comment by akosma** [comment]
This component must work with all Antora sites, for example the handbook, and doing so would break that behavior.

**Comment by chloesoe** [comment]
looks like your first proposed way to do it is the easiest and most straight-forward then. 
I'd say we should start with that.  Looking at your screenshot it looks like it is very easy to find out, what's the most recent version. So  I could just search for "X" first, then click on the newest version if I'm not satisfied with the search result. 

That's already an improvement. So for me OK to do that in a first iteration.

**Comment by davidgubler** [comment]
It looks to me like Antora isn't built to deploy more than one version of the documentation on the same Antora site, and the k8up documentation somehow abuses Antora. Maybe the real fix would be to not abuse Antora anymore and just deploy one version of the k8up documentation?

Other than that I agree with Daniel, it's certainly a big improvement if it works for version tags even if it doesn't work for master.

**Comment by akosma** [comment]
No, quite the opposite: Antora has been explicitly designed to support multiple versions, since version 1.0.
